ReminderModule/Controllers/EmailsetupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReminderModule.Data;
using ReminderModule.Data.Models;

namespace ReminderModule.Controllers
{
    public class EmailsetupsController : Controller
    {
        private readonly ReminderModuleContext _context;

        public EmailsetupsController(ReminderModuleContext context)
        {
            _context = context;
        }

        // GET: Emailsetups
        public async Task<IActionResult> Index()
        {
            return View(await _context.Emailsetup.ToListAsync());
        }

        // GET: Emailsetups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailsetup = await _context.Emailsetup
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emailsetup == null)
            {
                return NotFound();
            }

            return View(emailsetup);
        }

        // GET: Emailsetups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Emailsetups/Create        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Emailsetup emailsetup)
        {
            if (ModelState.IsValid)
            {
                _context.Add(emailsetup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(emailsetup);
        }

        // GET: Emailsetups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var savestatus = TempData["savestatus"];
            if (savestatus != null)
            {
                if (savestatus.ToString() == "OK")
                {
                    ViewBag.savestatus = "OK";
                }
            }
            
            
            var emailsetup = await _context.Emailsetup.FindAsync(id);
            if (emailsetup == null)
            {
                return NotFound();
            }
            return View(emailsetup);
        }

        // POST: Emailsetups/Edit/5        
        [HttpPost]
        [ValidateAntiForgeryToken]        
        public async Task<IActionResult> Edit(int id, Emailsetup emailsetup)
        {
            if (id != emailsetup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(emailsetup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmailsetupExists(emailsetup.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["savestatus"] = "OK";
                TempData.Keep();
                return RedirectToAction(nameof(Edit), id);
            }
            return View(emailsetup);
        }

        // GET: Emailsetups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailsetup = await _context.Emailsetup
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emailsetup == null)
            {
                return NotFound();
            }

            return View(emailsetup);
        }

        // POST: Emailsetups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var emailsetup = await _context.Emailsetup.FindAsync(id);
            if (emailsetup != null)
            {
                _context.Emailsetup.Remove(emailsetup);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmailsetupExists(int id)
        {
            return _context.Emailsetup.Any(e => e.Id == id);
        }
    }
}

ReminderModule/Controllers/RemindersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReminderModule.Data;
using ReminderModule.Data.Models;

namespace ReminderModule.Controllers
{
    public class RemindersController : Controller
    {
        private readonly ReminderModuleContext _context;

        public RemindersController(ReminderModuleContext context)
        {
            _context = context;
        }

        // GET: Reminders
        public async Task<IActionResult> Index()
        {
            return View(await _context.Reminder.ToListAsync());
        }

        // GET: Reminders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound($"Reminder with ID {id} not found.");
            }

            var reminder = await _context.Reminder
                .FirstOrDefaultAsync(m => m.ReminderId == id);
            if (reminder == null)
            {
                return NotFound($"Reminder with ID {id} not found.");
            }

            return View(reminder);
        }

        // GET: Reminders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reminders/Create        
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Bind("ReminderId,Title,ReminderDateTime,EmailSent")]
        public async Task<IActionResult> Create(Reminder reminder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reminder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reminder);
        }

        // GET: Reminders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reminder = await _context.Reminder.FindAsync(id);
            if (reminder == null)
            {
                return NotFound();
            }
            return View(reminder);
        }

        // POST: Reminders/Edit/5        
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Bind("ReminderId,Title,ReminderDateTime,EmailSent")]
        public async Task<IActionResult> Edit(int id, Reminder reminder)
        {
            if (id != reminder.ReminderId)
            {
                return NotFound($"Reminder with ID {id} not found.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reminder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReminderExists(reminder.ReminderId))
                    {
                        return NotFound($"Reminder with ID {reminder.ReminderId} not found.");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reminder);
        }

        // GET: Reminders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound($"Reminder with ID {id} not found.");
            }

            var reminder = await _context.Reminder
                .FirstOrDefaultAsync(m => m.ReminderId == id);
            if (reminder == null)
            {
                return NotFound($"Reminder with ID {id} not found.");
            }

            return View(reminder);
        }

        // POST: Reminders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reminder = await _context.Reminder.FindAsync(id);
            if (reminder != null)
            {
                _context.Reminder.Remove(reminder);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReminderExists(int id)
        {
            return _context.Reminder.Any(e => e.ReminderId == id);
        }
    }
}

ReminderModule/Views/Reminders/Create.cshtml
@model ReminderModule.Data.Models.Reminder

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Reminder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReminderDateTime" class="control-label"></label>
                <input asp-for="ReminderDateTime" class="form-control" />
                <span asp-validation-for="ReminderDateTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input disabled class="form-check-input" asp-for="EmailSent" /> @Html.DisplayNameFor(model => model.EmailSent)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReminderModule/Views/Reminders/Delete.cshtml
@model ReminderModule.Data.Models.Reminder

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reminder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReminderDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReminderDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailSent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailSent)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReminderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ReminderModule/Views/Reminders/Details.cshtml
@model ReminderModule.Data.Models.Reminder

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Reminder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReminderDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReminderDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailSent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailSent)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ReminderId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ReminderModule/Views/Reminders/Edit.cshtml
@model ReminderModule.Data.Models.Reminder

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Reminder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReminderId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReminderDateTime" class="control-label"></label>
                <input asp-for="ReminderDateTime" class="form-control" />
                <span asp-validation-for="ReminderDateTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input disabled class="form-check-input" asp-for="EmailSent" /> @Html.DisplayNameFor(model => model.EmailSent)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReminderModule/Views/Reminders/Index.cshtml
@model IEnumerable<ReminderModule.Data.Models.Reminder>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a> | <a asp-controller="Emailsetups" asp-action="Edit" asp-route-id="1">Email Setup</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReminderDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailSent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReminderDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailSent)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ReminderId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ReminderId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ReminderId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>